# Generated by Django 2.2.1 on 2019-05-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20190523_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='shop',
        ),
        migrations.AddField(
            model_name='commodity',
            name='shop',
            field=models.ManyToManyField(to='Store.Store'),
        ),
    ]
