# Generated by Django 2.2.1 on 2019-05-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycar',
            name='shop_id',
            field=models.IntegerField(default=1),
        ),
    ]
