# Generated by Django 2.2.1 on 2019-05-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_buycar_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='recver',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
