# Generated by Django 2.2.1 on 2019-05-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_auto_20190523_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycar',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
