# Generated by Django 2.2.1 on 2019-05-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_buycar_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buycar',
            name='buyuser_id',
        ),
    ]
