# Generated by Django 2.2.1 on 2019-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_remove_buycar_buyuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('loginName', models.CharField(max_length=32)),
                ('time', models.FloatField()),
                ('flag', models.CharField(max_length=4)),
            ],
        ),
    ]
