# Generated by Django 2.2.1 on 2019-05-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0006_validcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='money',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(),
        ),
    ]
